# Generated by Django 6.1 on 2026-08-14 14:11

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Woman'), ('M', 'Man'), ('O', 'Other')], max_length=1)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(120), django.core.validators.MaxValueValidator(230)], verbose_name='height (cm)')),
                ('marital_status', models.CharField(blank=True, choices=[('never', 'Never married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=16)),
                ('religion', models.CharField(blank=True, max_length=60)),
                ('community', models.CharField(blank=True, help_text='Caste, sub-community or denomination.', max_length=60)),
                ('mother_tongue', models.CharField(blank=True, max_length=60)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('education', models.CharField(blank=True, max_length=120)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('about', models.TextField(blank=True, max_length=2000, verbose_name='about me')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=profiles.models.photo_upload_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.profile')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'uploaded_at'],
            },
        ),
    ]
